config/routes.rb
SampleApp::Application.routes.draw do

  get "messages/new"
  resources :users do
    member do
      get :following
    end
  end
  resources :houses
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :microposts
  resources :messages
  root  'static_pages#home'
  match '/inbox',     to: 'users#inbox',          via: 'get'
  match '/results',   to: 'house#index',          via: 'get'
  match '/listhouse', to: 'houses#new',           via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/faq',       to: 'static_pages#faq',     via: 'get'

  mount Attachinary::Engine => "/attachinary"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def faq
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<ul>
  <li><%= link_to "Help links", '#' %></li>
  <li><%= link_to "Terms of Use", '#' %></li>
  <li><%= link_to "Privacy Policy", '#' %></li>
  <li><%= link_to "Contact Form", '#' %></li>
  <li><%= link_to "Fact Sheet", faq_path %></li>

</ul>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
  If you have any questions, comments concerns, please contact us at (310) 555-5555 or fake_email@bull.shit
</p>

app/views/static_pages/faq.html.erb
<h1>Fact Sheet</h1>
<body>
	Question:  Do you hate traditional Real Estate Agents? <br>
Answer:  No, not at all.  We think they can perform a valuable service.  We just think that the Real Estate market is late and slow in changing their model in today's information and Internet based world. <br><br>
Q.  Any examples of what you mean by changing the model?<br>
A.  Stock brokers pre internet charged a percentage or commission to buy or sale shares of stock.  For the most part, regular people could not trade stocks without paying these fees.  The Internet changed all that and now trading stocks is either very, very inexpensive or completely free.  And the volume of stock trades has gone from a few million shares traded a day to over a billion traded a day regularly.  Stock brokers jobs have evolved to consultants, money managers, and more.  And the people and economy are better off because of this evolution.<br><br>
Q.  What is the new recommended Real Estate model?<br>
A.  Rather than pay a fee to a real estate agent for listing or accessing the list, hire a Real Estate agent that meets your needs and pay them a fair fee for their service(s)<br><br>
Q.  What services roles and functions could the real estate perform?<br>
A.  The main one is being your consultant and helping you through the process.  Advising you as you go and connecting you to professionals in the various areas needed to sale or buy a home.  They may also help with marketing a home.  We don't feel that the traditional Real Estate role of charging you an exorbitant fee to be included in a list or access that list makes sense in today's Internet based, information accessible environment.<br><br>
Q.  Doesn't a Real Estate Agent perform all the functions needed to sell or buy a home and isn't that part of their fee?<br>
A.  No, the Real Estate fee is a listing or buying fee.  It may also include some marketing - creating a brochure, showing the house, etc. But it does not include several professional services needed to buy or sell a home.<br><br>
Q.   What are those other professional services needed to buy or sell a home?<br>
A.  Escrow - clearing house for payments, agreements, documentation and more:  Title insurance - insures legal ownership; Loan broker - helps acquire the loan;  Home Inspector; Termite service, Homeowner insurance are all professional services likely needed to buy or sell a home.<br><br>
Q.  What about answering questions as a seller from potential buyers?<br>
A.  Our system has a private email capability for questions - and you can publish questions received with their answers to a listing.  <br><br>
Q.  How about qualifying potential buyers?<br>
A.  Many sellers have buyers provide a bank letter or loan approval letter before answering too many questions or showing them the house.<br><br>
Q.  I am afraid to have someone in my home.<br>
A.  Hire someone - maybe a real estate agent or security person - to show the home for you.<br><br>
Q.  Any suggestions for when "looky loo's" or people that just want to see my home reach out to me?<br>
A.  Yes, have an open house.  Networking is a good thing and even looky loos may know someone who knows someone else.  Open houses are great ways to let people see your home and to market it.  Put up signs, list your open house in our site, maybe take out an ad in the local newspaper.  You may also want to hire security and print up a nice flyer or brochure.<br><br>
Q.  Any marketing tips?<br>
A.  Yes.  Historically marketing a home has been exclusively MLS driven and very private.  After all, one's home is a huge asset and people like some sort of privacy with their personal, financial matters.  But fact is home sales are already public information and anyone wanting to find details of a home sale can easily do so with a variety of Internet based queries.  Rather than continue the MLS based privacy, our suggestion for marketing is to open up the communication channels.  Let your friends know on Facebook.  Post in Nextdoor neighbors as well as any groups or boards you belong to. If someone at your church reads about your listing they may know someone who knows someone that could be interested.  Open up today's world to your home marketing.<br><br>
Q:  Is the housing data entered verified or otherwise checked for correctness?<br>
A:  Like the existing MLS, there is no verification of housing information listed.  Escrow and title insurance are used in both the existing, MLS based real estate system and for users of our site to verify data.<br><br>
Q.  Why are you doing this site?<br>
A.  It is time.  We want to make it easier, faster, and way more reasonable to sell or buy a home. It will help people as the cost of buy or selling a home will drop dramatically.  It will also stimulate the economy, create jobs, and make people happier.  We like that.<br><br>
Q.  Are you a for profit company?<br>
A.  Yes.  Eventually we plan to show unobtrusive ads on our site.<br><br>
Q.  Any tips for communicating between potential buyer and seller?<br>
A.  Yes.  Our experience is that buyers and sellers communicate and get along on everything with the exception of negotiating the price.  After all price is the ultimate zero sum or win/lose game.  We suggest hiring a good real estate agent to negotiate with potential buyers or sellers on your behalf.  <br><br>
</body>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
  <div="Howto">
   <p>How to...</p>
</div>
<ul>
  <li><%= link_to "Create a profile", '#' %></li>
  <li><%= link_to "Create your listing", '#' %></li>
  <li><%= link_to "Modify your listing", '#' %></li>
  <li><%= link_to "Search for listings", '#' %></li>
  <li><%= link_to "Save your listing search", '#' %></li>
</ul>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Robert's Real Estate</h1>
  <h2>
    The way real estate should be
      <br>
      <br>
      <br>
    <div class="home_search">
    <%= search_form_for @search do |f| %>

      <%= f.select :listing_type_cont, options_for_select(%w[Rent Buy], selected: 'Buy'), :include_blank => true %> 

      <%= f.text_field :address_or_city_cont, :placeholder => 'Enter Street Address OR City' %>

      <%= f.submit "Search Homes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
  
  </h2>
</div>
<div class="home_signin">
  <% if signed_in? %>
	  <%= link_to "Post New Listing", listhouse_path, class: "btn btn-large btn-primary" %> 
  <% else %>
  	<%= link_to "Sign up now to list your home", signup_path, class: "btn btn-large btn-primary" %> 
  <br>
  <br>
  or <%= link_to "Sign In", signin_path %> if you already have an account
  <% end %>
  <h2>
    <div class= "home_quote">
    <br><br><br>
    The original idea of the web was that it should be a collaborative space where you can communicate through sharing information free of charge.
    <br><br>
    - Tim Berners-Lee, founder of the Internet.
    <div>
  </h3>
</div>