config/routes.rb
SampleApp::Application.routes.draw do

  get "messages/new"
  resources :users do
    member do
      get :following
    end
  end
  resources :houses
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :microposts
  resources :messages
  root  'static_pages#home'
  match '/inbox',     to: 'users#inbox',          via: 'get'
  match '/results',   to: 'house#index',          via: 'get'
  match '/listhouse', to: 'houses#new',           via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/faq',       to: 'static_pages#faq',     via: 'get'

  mount Attachinary::Engine => "/attachinary"

end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  
  def new
  	@house = House.new
  end

  def index
    @search = House.search(params[:q])
    @search.sorts = ['zip asc', 'address desc'] if @search.sorts.empty?
    @houses = @search.result.paginate(page: params[:page], per_page: 15)  # load all matching records
  end

  def show
  	@house = House.find(params[:id])
    receiver = User.find(@house.user_id)
    @micropost = receiver.microposts.build
  end

  def edit
    @house = House.find(params[:id])
  end

  def create
    @house = current_user.houses.build(house_params)
    if @house.save
      flash[:success] = "Successful Listing!"
      redirect_to @house
    else
      render 'new'
    end
  end

  def update
    @house = House.find(params[:id])
    if @house.update_attributes(house_params)
      flash[:success] = "Listing updated"
      redirect_to @house
    else
      render 'edit'
    end
  end

  private

    def house_params
      params.require(:house).permit(:address, :price, :state, :county, 
                            :beds, :baths, :square_footage, :lot_size, 
                            :heating_type, :air_conditioning, :garage, 
                            :flooring, :year_built, :basement, :attic, 
                            :parking ,:fireplaces, :appliances, 
                            :house_type, :description, :zip, :city,
                            :floors, :picture, :status, :listing_type, {photos: []})
    end

end

app/helpers/houses_helper.rb
module HousesHelper
end

app/views/houses/_error_messages.html.erb
<% if @house.errors.any? %>
  <div id="error_explanation">
  	<div class="alert alert-error">
  	  The form contains <%= pluralize(@house.errors.count, "error") %>.
  	</div>
  	<ul>
  	<% @house.errors.full_messages.each do |msg| %>
  	  <li>* <%= msg %></li>
  	<% end %>
    </ul>
  </div>
<% end %>

app/views/houses/_follow.html.erb
<%= form_for(@house.relationships.build(followed_id: current_user.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "Favorite Home", class: "btn btn-large btn-primary" %>
<% end %>

app/views/houses/_house.html.erb
<li>
  <%= link_to "#{house.address}, #{house.city}, #{house.state}", house %>

  <% if current_user && current_user.id == house.user_id %>
    | (<%= link_to "edit", edit_house_path(house) %>)
  <% end %>
</li>

app/views/houses/_unfollow.html.erb
<% @house.relationships.find_by(followed_id: current_user.id) %>
<%= form_for(current_user.relationships.find_by(followed_id: @house.id), html: { method: :delete }) do |f| %>
  <%= f.submit "Favorited Home (click to unfavorite)", class: "btn btn-small" %>
<% end %>

app/views/houses/edit.html.erb
<% provide(:title, 'Edit Listing') %>
<h1>Edit Listing</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@house) do |f| %>
      <%= render 'houses/error_messages' %>

      <%= f.label :listing_type %>
      <%= f.select :listing_type, options_for_select(%w[Buy Rent]) %>

      <%= f.label "Upload photos" %>
      <%= f.attachinary_file_field :photos %>

      <%= f.label :status %>
      <%= f.select :status, options_for_select(["Please, buy my home.", "Seeing what's out there.", "Make me an offer!"]) %>

      <%= f.hidden_field :picture_cache %>
      <%= f.file_field :picture %>

      <%= f.label :street_address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>
      
      <%= f.label :state %>
      <%= f.select :state, options_for_select(%w[AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY], selected: @house.state) %>

      <%= f.label :zip %>
      <%= f.number_field :zip, max: 99999 %>

      <%= f.label :county %>
      <%= f.text_field :county %>

      <%= f.label :year_built %>
      <%= f.number_field :year_built %>

      <%= f.label :beds %>
      <%= f.number_field(:beds, in: 0.0..9.0, step: 0.5) %> 

	    <%= f.label :baths %>
      <%= f.number_field(:baths, in: 0.0..9.0, step: 0.25) %> 

      <%= f.label :price %>
      <%= f.number_field :price %>

      <label>Size (e.g. 8,500 sqft)</label>
      <%= f.text_field :square_footage %>

      <label>Lot Size (e.g. 1.5 acres)</label>
      <%= f.text_field :lot_size %>

      <%= f.label :floors %>
      <%= f.select :floors, (1..5) %>

      <%= f.label :house_type %>
	    <%= f.select :house_type, options_for_select(%w[Single-Family Duplex Triplex Condo Townhouse Land Other]) %> 

	    <%= f.label :flooring %>
	    <%= f.select :flooring, options_for_select(%w[Carpet Hardwood Laminate Tile]) %> 

	    <%= f.label :fireplaces %>
      <%= f.select :fireplaces, (0..9) %>

	    <%= f.label :heating_type %>
	    <%= f.select :heating_type, options_for_select(%w[None Central]) %>

      <%= f.label :air_conditioning %>
	    <%= f.select :air_conditioning, options_for_select(%w[None Central]) %>

      <%= f.label :garage %>
	    <%= f.select :garage, options_for_select(%w[None Attached Separate]) %>

	    <%= f.label :basement %>
	    <%= f.select :basement, options_for_select(%w[No Yes]) %>

	    <%= f.label :attic %>
	    <%= f.select :attic, options_for_select(%w[No Yes]) %>  

	    <%= f.label :parking %>
      <%= f.text_field :parking %>

	    <%= f.label :appliances %>
      <%= f.text_field :appliances %>

      <%= f.label :owner_description %>
      <%= f.text_field :description %>

      <br><br>

      <%= f.submit "Save Changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/houses/index.html.erb
<% provide(:title, 'Search Listings') %>

<h1>Robert's Real Estate</h1>
    
  <h3>Quick Search</h3>
  <div class="home_search">
    <%= search_form_for @search do |f| %>

      <%= f.select :listing_type_cont, options_for_select(%w[Rent Buy], selected: 'Buy'), :include_blank => true %> 

      <%= f.text_field :address_or_city_cont, :placeholder => 'Enter Street Address OR City' %>

      <%= f.submit "Search Homes", class: "btn btn-medium btn-primary" %>

    <% end %>
  </div>
  <br><button type="button" class="btn btn-default btn-lg" id="advanced_search">
  <span class="glyphicon glyphicon-search"></span> Advanced Search
</button>

<div class="advanced_search">
  <h3>Advanced Search</h3>
  <%= search_form_for @search do |f| %>
  <div class="row">
    <div class="span5">

    	<%= f.label :city_cont, "City" %>
    	<%= f.text_field :city_cont %>

      <%= f.label :state_cont, "State" %>
      <%= f.select :state_cont, options_for_select(%w[ AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY], selected: 'CA') %> 

    	<%= f.label :zip_eq, "Zip" %>
    	<%= f.text_field :zip_eq %>

    </div>
  </div>
  <div class="form-inline">
      <%= f.label :price_gteq, "Price" %>
      <br>
      <%= f.text_field :price_gteq, :placeholder => 'Minimum Price' %>
    	<%= f.text_field :price_lteq, :placeholder => 'Maximum Price' %>
  </div>
    <br>
      <%= f.select :listing_type_cont, options_for_select(%w[Rent Buy]), :include_blank => true %> 

    <br>
    <%= f.submit "Search", class: "btn btn-medium btn-primary" %>
    </div>
  </div>
  <% end %>
</div>
<br>

<div class="results">
<%= will_paginate %>

<ul class="listings">
  <% @houses.each do |house| %>
    <li>
        <div class="listing_pic">
          <% if house.photos.first %>
            <% photo = house.photos.first %>
            <%= image_tag "http://res.cloudinary.com/roberts-real-estate/image/upload/w_150,h_120,c_thumb/#{photo.path}" %>
          <% else %>
            .
          <% end %>
        </div>
        <div class="house_textinfo">
        <div class="house_address">
          <% if house.zip %>
          <%= link_to "#{house.address}", house %>
          <% end %>
        </div>
        <div class="house_price">
          <% if house.zip %>
            $<%= number_with_delimiter(house.price, :delimiter => ',')%>
          <% end %>
        </div>
        <div class="house_citystate line">
          <%= "#{house.city}, #{house.state}" %> <% if house.zip %> <%= "#{'%05d' % house.zip}" %> <% end %>
        </div>
        <br>
        <div class="house_bedbathsize line">
          <%= "#{house.beds} beds  |   #{house.baths} baths   |   " %>
          <%= number_with_delimiter((house.square_footage).to_i, :delimiter => ',') %> sqft
        </div>
    </li>
  <% end %>
</ul>

<%= will_paginate %>
</div>

<script src="assets/advanced_search.js"></script>

app/views/houses/new.html.erb
<% provide(:title, 'List House') %>
<h1>List House</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@house) do |f| %>
      <%= render 'houses/error_messages' %>

      <%= f.label :listing_type %>
      <%= f.select :listing_type, options_for_select(%w[Buy Rent]) %> 

      <%= f.label "Upload photos" %>
      <%= f.attachinary_file_field :photos %>
    
      <%= f.label :status %>
      <%= f.select :status, options_for_select(["Please, buy my home.", "Seeing what's out there.", "Make me an offer!"]) %>
      
      <%= f.label :street_address %>
      <%= f.text_field :address %>

      <%= f.label :city %>
      <%= f.text_field :city %>
      
      <%= f.label :state %>
      <%= f.select :state, options_for_select(%w[ AL AK AZ AR CA CO CT DE FL GA HI ID IL IN IA KS KY LA ME MD MA MI MN MS MO MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VT VA WA WV WI WY], selected: 'CA') %>

      <%= f.label :zip %>
      <%= f.number_field :zip, max: 99999 %>

      <%= f.label :county %>
      <%= f.text_field :county %>

      <%= f.label :year_built %>
      <%= f.number_field :year_built %>

      <%= f.label :beds %>
      <%= f.number_field(:beds, in: 0.0..9.0, step: 0.5) %> 

	<%= f.label :baths %>
      <%= f.number_field(:baths, in: 0.0..9.0, step: 0.25) %> 

      <%= f.label :price %>
      <%= f.number_field :price %>


      <%= f.label :square_footage %>
      <%= f.text_field :square_footage, :placeholder => 'e.g. 8,500 sqft' %>

      <%= f.label :lot_size %>
      <%= f.text_field :lot_size, :placeholder => 'e.g. 1.5 acres' %>

      <%= f.label :floors %>
      <%= f.select :floors, (1..5) %>

      <%= f.label :house_type %>
	    <%= f.select :house_type, options_for_select(%w[Single-Family Duplex Triplex Condo Townhouse Land Other]) %> 

	<%= f.label :flooring %>
	<%= f.select :flooring, options_for_select(%w[Carpet Hardwood Laminate Tile]) %> 

	<%= f.label :fireplaces %>
      <%= f.select :fireplaces, (0..9) %>

	<%= f.label :heating_type %>
	<%= f.select :heating_type, options_for_select(%w[None Central]) %>

      <%= f.label :air_conditioning %>
	<%= f.select :air_conditioning, options_for_select(%w[None Central]) %>

      <%= f.label :garage %>
      <%= f.select :garage, options_for_select(%w[None Attached Separate]) %>

      <%= f.label :basement %>
      <%= f.select :basement, options_for_select(%w[No Yes]) %>

      <%= f.label :attic %>
      <%= f.select :attic, options_for_select(%w[No Yes]) %>  

      <%= f.label :parking %>
      <%= f.text_field :parking %>

	<%= f.label :appliances %>
      <%= f.text_field :appliances %>

	<%= f.label :owner_description %>
      <%= f.text_field :description %>

      <br><br>
      <%= f.submit "Post Listing", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>

</div>

<script src="assets/multiple-image.js"></script>
<script src="assets/attach.js"></script>

app/views/houses/show.html.erb
<% provide(:title, @house.address) %>

<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">  
    <div class="rg-image-wrapper">
        {{if itemsCount > 1}}
            <div class="rg-image-nav">
                <a href="#" class="rg-image-nav-prev">Previous Image</a>
                <a href="#" class="rg-image-nav-next">Next Image</a>
            </div>
        {{/if}}
        <div class="rg-image"></div>
        <div class="rg-loading"></div>
        <div class="rg-caption-wrapper">
            <div class="rg-caption" style="display:none;">
                <p></p>
            </div>
        </div>
    </div>
</script>


<h1><%= @house.address %></h1>
<p><center><%= @house.city %>, <%= @house.state %>  <%= "%05d" % @house.zip %></center></p>
<p><center><%= @house.status %>  Asking Price: $<%= number_with_delimiter(@house.price, :delimiter => ',') %></center></p>



<% if not @house.photos.present? %>
  <center><%= image_tag "http://maps.googleapis.com/maps/api/streetview?size=600x450&location=#{@house.address.split.join('+')},#{@house.city.split.join('+')}+#{@house.state}&fov=90&pitch=0" %></center>
<br>
<% else %>
  

  <div id="rg-gallery" class="rg-gallery">
    <div class="rg-thumbs">
        <!-- Elastislide Carousel Thumbnail Viewer -->
        <div class="es-carousel-wrapper">
            <div class="es-nav">
                <span class="es-nav-prev">Previous</span>
                <span class="es-nav-next">Next</span>
            </div>
            <div class="es-carousel">
                <ul>
                    <% i = 0 %>
                    <% @house.photos.each do |photo| %>
                    <li>
                      <% i+=1 %>
                      <a href="#">

                            <img src='http://res.cloudinary.com/roberts-real-estate/image/upload/w_90,h_90,c_thumb/<%= photo.path %>' data-large='http://res.cloudinary.com/roberts-real-estate/image/upload/w_800,h_500,c_fit/<%= photo.path %>' alt="image02" data-description="Photo <%= i %>" /></a>

                    </li>
                    <% end %>
                </ul>
            </div>
        </div>
        <!-- End Elastislide Carousel Thumbnail Viewer -->
    </div><!-- rg-thumbs -->
</div><!-- rg-gallery -->


<% end %>



<center>
  <% if signed_in? %>
    <div id="follow_form">
    <% if current_user.following?(@house) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
    </div>
  <% else %>
    <%= link_to "Sign Up or Sign In to favorite a home", signup_path, class: "btn btn-medium btn-primary" %> 
  <% end %>
</center>

<br>

<h3>Owner Description</h3>
<body><%= @house.description %></body>


<br><br>
<h3>Property Overview</h3>
<table class="table table-striped table-bordered table-condensed">
<tr>
  <td> Sq Ft: <%= number_with_delimiter((@house.square_footage).to_i, :delimiter => ',') %>  </td>
  <td>Lot Size: <%= @house.lot_size %> </td>		
  <td>Type: <%= @house.house_type %></td>
</tr>
<tr>
  <td><%= @house.beds %> bedrooms</td>
  <td>Built in <%= @house.year_built %></td>		
  <td>Heating: <%= @house.heating_type %></td>
</tr>
<tr>
  <td><%= @house.baths %> bathrooms</td>
  <td>Air Conditioning: <%= @house.air_conditioning %></td>		
  <td>Garage: <%= @house.garage %></td>
</tr>
<tr>
  <td>Attic: <%= @house.attic %></td>
  <td>Basement: <%= @house.basement %></td>		
  <td>Fireplaces: <%= @house.fireplaces %></td>
</tr>
<tr>
  <td>Flooring: <%= @house.flooring %></td>
  <td># of Floors: <%= @house.floors %></td>
  <td></td>		
</tr>
</table>
<table class="table table-striped table-bordered table-condensed">
  <tr>
  <td> Appliances: <%= @house.appliances %></td>
  </tr>
  <tr>
  <td> Parking: <%= @house.parking %></td>
</tr>
</table>
<body>
   <br><br>
  
</html>

<br><br>

<center><iframe
  width="600"
  height="450"
  zoom="19"
  maptype="satellite"
  frameborder="0" style="border:0"
  src=<%= "https://www.google.com/maps/embed/v1/place?key=AIzaSyBqejMuiEdMR24e-79FhVgQdOvzYHD0Low&q=#{@house.address.split.join('+')},#{@house.city.split.join('+')}+#{@house.state}" %>>
</iframe></center>
<br><br>

<h3>Contact the Owner</h3>
<% if signed_in? %>
  <%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="micropost-form">
      <%= f.text_area :content, placeholder: "Send a Message", :rows => 10 %>

      <%= f.hidden_field :user_id, :value => @house.user_id %>

      <%= f.hidden_field :sender_id, :value => current_user.id %>

      <%= f.hidden_field :unread, :value => true %>

    </div>
    <%= f.submit "Send Message", class: "btn btn-medium btn-primary" %>
  <% end %>
<% else %>
  <%= link_to "Sign up or Sign In to contact the owner", signup_path, class: "btn btn-medium btn-primary" %> 
<% end %>

<script src="assets/gallery.js"></script>